repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: \.ya?ml$
      - id: trailing-whitespace
        exclude: \.ya?ml$
      - id: check-case-conflict
        exclude: \.ya?ml$
      - id: check-merge-conflict
        exclude: \.ya?ml$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
      - id: clang-format
        name: Formating C files with Clang-Format
        exclude: \.ya?ml$
